name: ${model.name}-${data.name}
data:
  name: sentiment-marketing
  path: data/${data.name}
  invalid_chars: ['rt:', '@', '#']
  max_length: 256
model:
  name: bert-fa-zwnj-base
  lm_path: 'weights/${name}'
train:
  device: 'cpu'
  batch_size: 16
  lr: 2e-5
  num_epochs: 10
  ckpt_dir: 'checkpoints/${model.name}/${data.name}'
  save_ckpt_freq: 1
  log_dir: 'logs'
inference:
  device: 'cpu'
  weights_path: 'weights/${model.name}-${data.name}'
