name: sentiment_marketing
model_name: bert-fa-zwnj-base
device: 'cuda'
lm_checkpoint: 'weights/${model_name}'
data_path: 'data/${name}'
batch_size: 16
max_length: 256
invalid_chars: ['rt:', '@', '#']
lr: 2e-5
num_epochs: 10
save_ckpt_freq: 1
ckpt_dir: 'checkpoints/${name}/${model_name}'
weight_path: 'checkpoints/${name}/${model_name}/5'
log_dir: 'logs'
